services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.fast
    ports:
      - "8000:8000"
    volumes:
      # Mount the models directory so Docker can access your ML models
      - ../model:/app/models-source
      - ./models:/app/models
      - ./storage:/app/storage
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - 'ALLOWED_ORIGINS=["http://localhost:3000","http://localhost:3001"]'
      - MODEL_PATH=/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s