services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
      - MODEL_PATH=/app/models
    volumes:
      # Mount the models directory so Docker can access your ML models
      - ../model:/app/models-source
      - ./models:/app/models
      - ./storage:/app/storage
      - ./app:/app/app:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s