[phases.setup]
nixPkgs = ["python311", "pip", "gcc", "curl"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements-railway.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python main.py"

[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
NIXPACKS_PYTHON_VERSION = "3.11"