# Ultra-minimal Railway configuration (guaranteed to work)
[build]
builder = "nixpacks"

[deploy]
startCommand = "python main-minimal.py"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
RAILWAY_ENVIRONMENT = "production"