# Alternative Railway configuration using Nixpacks (faster builds)
[build]
builder = "nixpacks"

[deploy]
startCommand = "python main-railway.py"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
RAILWAY_ENVIRONMENT = "production"
NIXPACKS_PYTHON_VERSION = "3.11"